"""Transfer owner colum

Revision ID: 7330f2e20395
Revises: 34ebbed575c6
Create Date: 2022-07-19 13:59:09.647797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7330f2e20395'
down_revision = '34ebbed575c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('owner', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transfers', 'users', ['owner'], ['ID_Usr'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'owner')
    # ### end Alembic commands ###
