version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
  postgres:
    image: postgres
    ports:
      - 6000:5432
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=BudgetApp
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
  

volumes:
  postgres-db: