version: '3'
services:
  client:
    build: ./Client
    restart: unless-stopped
    ports:
      - 5000:5000
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=BudgetApp
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./API/.env

volumes:
  postgres-db:
