"""many to many fix

Revision ID: 467ea8a06897
Revises: 90c8ce9216e0
Create Date: 2022-04-28 18:13:55.556526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467ea8a06897'
down_revision = '90c8ce9216e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_owner_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('accounts_owner_fkey', 'accounts', 'users', ['owner'], ['ID_Usr'])
    # ### end Alembic commands ###
