"""Initial revision

Revision ID: 90c8ce9216e0
Revises: 
Create Date: 2022-04-28 17:49:04.505577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c8ce9216e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID_Usr', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ID_Usr')
    )
    op.create_table('accounts',
    sa.Column('ID_Acc', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.ID_Usr'], ),
    sa.PrimaryKeyConstraint('ID_Acc')
    )
    op.create_table('categories',
    sa.Column('ID_Cat', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.ID_Usr'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_Cat')
    )
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.ID_Acc'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.ID_Usr'], )
    )
    op.create_table('predictions',
    sa.Column('ID_Pred', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(decimal_return_scale=2), nullable=False),
    sa.Column('purpose_of_the_expendture', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.ID_Acc'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category'], ['categories.ID_Cat'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.ID_Usr'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_Pred')
    )
    op.create_table('transfers',
    sa.Column('ID_Tr', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(decimal_return_scale=2), nullable=False),
    sa.Column('from_account', sa.Integer(), nullable=False),
    sa.Column('to_account', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_account'], ['accounts.ID_Acc'], ),
    sa.ForeignKeyConstraint(['to_account'], ['accounts.ID_Acc'], ),
    sa.PrimaryKeyConstraint('ID_Tr')
    )
    op.create_table('operations',
    sa.Column('ID_Op', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(decimal_return_scale=2), nullable=False),
    sa.Column('purpose_of_the_expendture', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.ID_Acc'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category'], ['categories.ID_Cat'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.ID_Usr'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction'], ['predictions.ID_Pred'], ),
    sa.PrimaryKeyConstraint('ID_Op')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('transfers')
    op.drop_table('predictions')
    op.drop_table('association')
    op.drop_table('categories')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
