"""Currency added

Revision ID: c42035b914e3
Revises: 7330f2e20395
Create Date: 2022-09-02 13:15:40.257471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42035b914e3'
down_revision = '7330f2e20395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency', sa.String(length=3), server_default='PLN', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'currency')
    # ### end Alembic commands ###
